version: "3.7"

services:
  database_obituary:
    image: postgres
    container_name: database_obituary
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=obituary
    volumes:
      - pgdata:/data/postgres
  app:  
    build: .
    container_name: obituary
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/app
    links:
      - database_obituary
    depends_on:   
      - database_obituary

volumes:
  pgdata:
    driver: local